<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="9" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-12-10T20:08:11 NZDT" name="All-Exception-Tests" finished-at="2019-12-10T20:08:38 NZDT" duration-ms="27081">
    <groups>
      <group name="exception-tests">
        <method signature="Login_Exceptions_Tests.stale_Element_Test_Exception()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@1a0dcaa]" name="stale_Element_Test_Exception" class="com.herokuapp.theinternet.Login_Exceptions_Tests"/>
      </group> <!-- exception-tests -->
    </groups>
    <test started-at="2019-12-10T20:08:11 NZDT" name="Login_Exception_Tests" finished-at="2019-12-10T20:08:22 NZDT" duration-ms="10724">
      <class name="com.herokuapp.theinternet.Login_Exceptions_Tests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@780cb77]" started-at="2019-12-10T20:08:11 NZDT" name="setUp" finished-at="2019-12-10T20:08:15 NZDT" duration-ms="4613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="dynamic_Loading()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@780cb77]" started-at="2019-12-10T20:08:15 NZDT" name="dynamic_Loading" finished-at="2019-12-10T20:08:21 NZDT" duration-ms="5984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dynamic_Loading -->
        <test-method is-config="true" signature="closeUp()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@780cb77]" started-at="2019-12-10T20:08:21 NZDT" name="closeUp" finished-at="2019-12-10T20:08:22 NZDT" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
      </class> <!-- com.herokuapp.theinternet.Login_Exceptions_Tests -->
    </test> <!-- Login_Exception_Tests -->
    <test started-at="2019-12-10T20:08:22 NZDT" name="Dynamic_Logout_Timeout" finished-at="2019-12-10T20:08:31 NZDT" duration-ms="9107">
      <class name="com.herokuapp.theinternet.Login_Exceptions_Tests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@15761df8]" started-at="2019-12-10T20:08:22 NZDT" name="setUp" finished-at="2019-12-10T20:08:28 NZDT" duration-ms="6094" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="dynamic_Loading_Timeout()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@15761df8]" started-at="2019-12-10T20:08:28 NZDT" name="dynamic_Loading_Timeout" finished-at="2019-12-10T20:08:31 NZDT" duration-ms="2921" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exception: The actual value is not as the expected value expected [Hello World!] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exception: The actual value is not as the expected value expected [Hello World!] but found []
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.herokuapp.theinternet.Login_Exceptions_Tests.dynamic_Loading_Timeout(Login_Exceptions_Tests.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dynamic_Loading_Timeout -->
        <test-method is-config="true" signature="closeUp()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@15761df8]" started-at="2019-12-10T20:08:31 NZDT" name="closeUp" finished-at="2019-12-10T20:08:31 NZDT" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
      </class> <!-- com.herokuapp.theinternet.Login_Exceptions_Tests -->
    </test> <!-- Dynamic_Logout_Timeout -->
    <test started-at="2019-12-10T20:08:31 NZDT" name="Stale_Element_Exception" finished-at="2019-12-10T20:08:38 NZDT" duration-ms="7186">
      <class name="com.herokuapp.theinternet.Login_Exceptions_Tests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@1a0dcaa]" started-at="2019-12-10T20:08:31 NZDT" name="setUp" finished-at="2019-12-10T20:08:35 NZDT" duration-ms="4057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="stale_Element_Test_Exception()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@1a0dcaa]" started-at="2019-12-10T20:08:35 NZDT" name="stale_Element_Test_Exception" finished-at="2019-12-10T20:08:38 NZDT" duration-ms="3044" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stale_Element_Test_Exception -->
        <test-method is-config="true" signature="closeUp()[pri:0, instance:com.herokuapp.theinternet.Login_Exceptions_Tests@1a0dcaa]" started-at="2019-12-10T20:08:38 NZDT" name="closeUp" finished-at="2019-12-10T20:08:38 NZDT" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
      </class> <!-- com.herokuapp.theinternet.Login_Exceptions_Tests -->
    </test> <!-- Stale_Element_Exception -->
  </suite> <!-- All-Exception-Tests -->
</testng-results>
